# Generated by Django 5.0.2 on 2024-03-08 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
                ('Number', models.IntegerField(max_length=20)),
                ('Date', models.DateField()),
                ('Person', models.IntegerField(max_length=10)),
            ],
        ),
    ]
